CREATE TABLE CITIES
(CityID int PRIMARY KEY, 
 City VARCHAR(50) NOT NULL, 
 );
 
CREATE TABLE STADIUMS
(StadiumID int PRIMARY KEY, 
 StadiumName VARCHAR(100) NOT NULL,
 StadiumCapacity INT 
 ); 

CREATE TABLE NATIONALITIES
(NationalityID int PRIMARY KEY, 
 Nationality VARCHAR(50) NOT NULL, 
 );

CREATE TABLE POSITIONS
(PositionID int PRIMARY KEY, 
 Position VARCHAR(50) NOT NULL, 
 );

CREATE TABLE TEAMS
(TeamID INT PRIMARY KEY, 
 TeamName VARCHAR(50) NOT NULL,
 TeamYear INT NOT NULL,
 CityID INT FOREIGN KEY REFERENCES CITIES(CityID),
 StadiumID INT FOREIGN KEY REFERENCES STADIUMS(StadiumID), 
 PresidentName VARCHAR(30),
 PresidentLast VARCHAR(30),
 CoachName VARCHAR(30),
 CoachLast VARCHAR(30)
);

CREATE TABLE PLAYERS
(PlayerID int PRIMARY KEY, 
 PlayerFirst VARCHAR(50),
 PlayerLast VARCHAR(50) NOT NULL,
 PlayerDateOB DATE,
 NatinalityID INT FOREIGN KEY REFERENCES NATIONALITIES(NationalityID),
 PositionID INT FOREIGN KEY REFERENCES POSITIONS(PositionID), 
 PlayerValue INT,
 TeamID INT FOREIGN KEY REFERENCES TEAMS(TeamID)
);

CREATE TABLE MATCHES
(MatchID int PRIMARY KEY, 
 MatchDate DATE,
 InTeamID INT FOREIGN KEY REFERENCES TEAMS(TeamID),
 OutTeamID INT FOREIGN KEY REFERENCES TEAMS(TeamID),
 InGoals INT,
 OutGoals INT
);

CREATE TABLE MATCH_PLAYER
(MatchID int FOREIGN KEY REFERENCES MATCHES(MatchID),
 PlayerID int FOREIGN KEY REFERENCES PLAYERS(PlayerID),
 TimePlayed INT,
 Goals INT, 
 Assists INT, 
 YelloCards INT,
 RedCards INT, 
 PRIMARY KEY (MatchID, PlayerID)
);